//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenPhongTan_2210900123.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Npt_TacGia
    {
        public string Npt_MaTG { get; set; }
        public string Npt_TenTG { get; set; }
    
        public virtual Npt_Sach Npt_Sach { get; set; }
    }
}
