//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenPhongTan_2210900123.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NguyenPhongTan_2210900123Entities : DbContext
    {
        public NguyenPhongTan_2210900123Entities()
            : base("name=NguyenPhongTan_2210900123Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Npt_Sach> Npt_Sach { get; set; }
        public virtual DbSet<Npt_TacGia> Npt_TacGia { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
