//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTGK_NguyenPhongTan_K22CNT3_2201900123.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nptSinhVien
    {
        public string nptMaSV { get; set; }
        public string nptHoSV { get; set; }
        public string nptTenSV { get; set; }
        public Nullable<System.DateTime> nptNgaySinh { get; set; }
        public Nullable<bool> nptPhai { get; set; }
        public string nptPhone { get; set; }
        public string nptEmail { get; set; }
        public string nptMaKH { get; set; }
    
        public virtual nptKhoa nptKhoa { get; set; }
    }
}
