//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NptK22CNT3Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NptAccount
    {
        public int NptId { get; set; }
        public string NptUserName { get; set; }
        public string NptPassword { get; set; }
        public string NptFullName { get; set; }
        public string NptEmail { get; set; }
        public string Nptphone { get; set; }
        public Nullable<bool> NptActive { get; set; }
    }
}
